[package]
name = "pciutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.1"
env_logger = "0.10.0"
log = "0.4.17"
pci-ids = "0.2.5"
pretty-hex = "0.3.0"

