[package]
name = "pciutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.1"
lazy_static = "1.4.0"
pci-ids = "0.2.5"
pretty-hex = "0.3.0"
regex = "1"

